apiVersion: v1
kind: Service
metadata:
  name: git-lfs-s3-proxy-svc
  namespace: git-lfs-s3-proxy
spec:
  type: NodePort
  selector:
    app: git-lfs-s3-proxy
  ports:
    - name: web
      port: 3000
      targetPort: 3000
      nodePort: 30092
