apiVersion: v1
kind: Service
metadata:
  name: weather-svc
  namespace: weather
spec:
  type: NodePort
  selector:
    app: weather
  ports:
    - name: web
      port: 3000
      targetPort: 3000
      nodePort: 30091
