apiVersion: apps/v1
kind: Deployment
metadata:
  name: jamchat
  namespace: jamchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jamchat
  template:
    metadata:
      labels:
        app: jamchat
    spec:
      imagePullSecrets: 
      - name: regcred
      containers:
      - name: jamchat
        image: repo.matzen.io/jamchat:latest
        imagePullPolicy: Always
        env:
        - name: GOOGLE_CLIENT_ID
          value: 1032475387376-sfs9iplm6rhbjj6am9ad53imc8r96nog.apps.googleusercontent.com
        - name: OAUTH_REDIRECT_URL
          value: https://chat.funotron.com/auth/google/callback
        - name: APP_BASE_URL
          value: https://chat.funotron.com
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: jamchat-secrets
              key: OPENAI_API_KEY
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: jamchat-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: jamchat-secrets
              key: COOKIE_SECRET
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: jamchat-pvc
          mountPath: /app/data
      volumes:
      - name: jamchat-pvc
        persistentVolumeClaim:
          claimName: jamchat-pvc
