apiVersion: apps/v1
kind: Deployment
metadata:
  name: jamchat
  namespace: jamchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jamchat
  template:
    metadata:
      labels:
        app: jamchat
    spec:
      initContainers:
      - name: init-db-permissions
        image: busybox  # Or any lightweight image with chown
        command: ['sh', '-c', 'chown -R 999:999 /app/data/chats.db']
        volumeMounts:
        - name: jamchat-pvc
          mountPath: /app/data
        securityContext:
          runAsUser: 0  # Run as root to perform chown
      imagePullSecrets: 
      - name: regcred
      containers:
      - name: jamchat
        image: repo.matzen.io/jamchat:latest
        imagePullPolicy: Always
        env:
        - name: RUST_LOG
          value: trace
        - name: GOOGLE_CLIENT_ID
          value: 1032475387376-sfs9iplm6rhbjj6am9ad53imc8r96nog.apps.googleusercontent.com
        - name: OAUTH_REDIRECT_URL
          value: https://chat.matzen.io/auth/google/callback
        - name: APP_BASE_URL
          value: https://chat.matzen.io
        - name: MODEL_FILTER_REGEX # MODEL_FILTER_REGEX=^gpt-5.2
          value: "^(gpt-5.2-|gpt-5-|claude.*4.5)"
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: anthropic-api
              key: ANTHROPIC_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: jamchat-secrets
              key: OPENAI_API_KEY
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: jamchat-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: jamchat-secrets
              key: COOKIE_SECRET
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts:
        - name: jamchat-pvc
          mountPath: /app/data
      volumes:
      - name: jamchat-pvc
        persistentVolumeClaim:
          claimName: jamchat-pvc
