apiVersion: v1
kind: Service
metadata:
  name: jamchat-svc
  namespace: jamchat
spec:
  type: NodePort
  selector:
    app: jamchat
  ports:
    - name: web
      port: 3000
      targetPort: 3000
      nodePort: 30090
